
kafka:

  # Security configuration (basic)
  auth:
    enabled: true
    clientProtocol: sasl_plaintext  # Can be changed to 'sasl_plaintext' or 'sasl_ssl' for security
    interBrokerProtocol: sasl
    sasl:
      mechanism: plain
      jaas:
        clientUsers:
          - "user1"
          - "user2"
        clientPasswords:
          - "password1"
          - "password2"
        interBrokerUser: "admin"
